-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 22:41:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuari`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuari` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuari` (
  `id_usuari` VARCHAR(45) GENERATED ALWAYS AS (),
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `usuari_id_usuari` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuari`),
  UNIQUE INDEX `id_usuari_UNIQUE` (`id_usuari` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuari_usuari_idx` (`usuari_id_usuari` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_usuari`
    FOREIGN KEY (`usuari_id_usuari`)
    REFERENCES `mydb`.`usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fotografies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fotografies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fotografies` (
  `id_foto` INT GENERATED ALWAYS AS (),
  `adreça` VARCHAR(45) NOT NULL,
  `codi` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `usuari_id_usuari` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_foto`),
  UNIQUE INDEX `id_foto_UNIQUE` (`id_foto` ASC) VISIBLE,
  UNIQUE INDEX `codi_UNIQUE` (`codi` ASC) VISIBLE,
  INDEX `fk_Fotografies_usuari1_idx` (`usuari_id_usuari` ASC) VISIBLE,
  CONSTRAINT `fk_Fotografies_usuari1`
    FOREIGN KEY (`usuari_id_usuari`)
    REFERENCES `mydb`.`usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveïdor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveïdor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveïdor` (
  `NIF` VARCHAR(9) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `pis` INT NOT NULL,
  `porta` INT UNSIGNED NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi postal` INT UNSIGNED NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telf.` INT UNSIGNED NOT NULL,
  `fax` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`NIF`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venedor` (
  `idvenedor` INT GENERATED ALWAYS AS (),
  PRIMARY KEY (`idvenedor`),
  UNIQUE INDEX `idvenedor_UNIQUE` (`idvenedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `nom` INT NOT NULL,
  `adreça postal` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data de registre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `idulleres` INT GENERATED ALWAYS AS (),
  `marca` VARCHAR(45) NOT NULL,
  `graduació esquerra` VARCHAR(45) NOT NULL,
  `graduació dret` VARCHAR(45) NOT NULL,
  `montura` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL COMMENT 'jhjkh,hjhj,hihiu',
  `color montura` VARCHAR(45) NOT NULL,
  `color vidre E` VARCHAR(45) NOT NULL,
  `color vidre D` VARCHAR(45) NOT NULL,
  `preu` VARCHAR(45) NOT NULL,
  `proveïdor_NIF` VARCHAR(9) NOT NULL,
  `venedor_idvenedor` INT UNSIGNED NOT NULL,
  `clients_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idulleres`, `proveïdor_NIF`, `venedor_idvenedor`, `clients_email`),
  INDEX `fk_ulleres_proveïdor1_idx` (`proveïdor_NIF` ASC) VISIBLE,
  UNIQUE INDEX `idulleres_UNIQUE` (`idulleres` ASC) VISIBLE,
  INDEX `fk_ulleres_venedor1_idx` (`venedor_idvenedor` ASC) VISIBLE,
  INDEX `fk_ulleres_clients1_idx` (`clients_email` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_proveïdor1`
    FOREIGN KEY (`proveïdor_NIF`)
    REFERENCES `mydb`.`proveïdor` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_venedor1`
    FOREIGN KEY (`venedor_idvenedor`)
    REFERENCES `mydb`.`venedor` (`idvenedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_clients1`
    FOREIGN KEY (`clients_email`)
    REFERENCES `mydb`.`clients` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
